# This file uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  # In order to generate a new key set for a new user, run the following commands:
  # ```sh
  # $ # on linux:
  # $ sops_dir=~/".config/sops/age"
  # $ # on macOS:
  # $ sops_dir=~/"Library/Application Support/sops/age"
  # $ mkdir -p "$sops_dir"
  # $ age-keygen -o "$sops_dir/keys.txt"
  # $ cat "$sops_dir/keys.txt" | sed -nEe 's/.+public key:\s+(.*)$/\1/mip'
  # ```
  # Then add that value to a new key here:
  users:
    - &user_dudeofawesome 'age17dnfg660q6f6xv634dlsqzt9arungk5k3xytd68m2c94tqa3wqtqv7ew0d'
    - &user_josh 'age1nu45m5ht7x7h59t4x8kalx9j084tqty27rw97xl63fp85l8w45qspgdqt0'

  # In order to generate a new public key for a new system, run the following commands:
  # ```sh
  # $ ssh-keyscan DEVICE_HOSTNAME 2> /dev/null | ssh-to-age 2> /dev/null | sed -nEe 's/(age.+)/\1/mip'
  # ```
  # Then add that value to a new key here:
  systems:
    - &system_badlands 'age16juvzqnt7qs5pkssaqltlwn9e4chk3w9zf8gcazmcj7uu3tmcg9q3f2yp7'
    - &system_badlands-vm 'age1dfekdgq7ksy6v96a2h2p5ml09emrgdlwxmcsm2d3c0am49y2vynqak40ss'
    - &system_crater-lake 'age1rqjddanhdhc3gvj9mj9ez5cm492uqtcnj9elljpp4uy4hx4p3sgqyyfxa6'
    - &system_monongahela 'age1r3z0gd3fmq5vu73l7k7jsseaz5ec8f88qq5sw0zvlexug6uzf4wsadjrhx'
    - &system_haleakala 'age1wy9vrp4k3w69dtjfeskayrn4m4m6fntjcj480junfvpjflnd0p8sg078qc'
    - &system_joshs-paciolan-laptop 'age1ct6h645xhzamd5mfhs5ze8uza2k23tjat8wrrrn7k6sakr5uecjs7u8j35'
    - &system_soto-server 'age1a4z2qgdtv8aaqe0892clncuz4kpdqn9ph2qqg6k850hxl2lqrd2shu7mgs'
    # - &system_starling-vm 'age1nm4qzu0srzff2zylgr46j7fjpr5kprz7huvzwwwqxny42nr6ydvskejjx4' # Qemu VM
    # - &system_starling-vm 'age1w7ny9w9v5p5g4d6lcdcg2eayxm2gjrnvn55g6syrjkkqg98c9y6syz88ty' # Parallels VM (NixOS)
    - &system_starling-vm 'age12zmhesaygdrw509e78wgpcut8f96cmjyvmequcwz5kl5wwfhgd0skr7a2n' # Parallels VM (NixOS-Anywhere Demo)

  # When adding new keys, make sure to update the encrypted files:
  # `sops updatekeys ENCRYPTED_FILE`
  # https://github.com/getsops/sops#27adding-and-removing-keys
  # or, to update all files:
  # `find . \( -wholename "*/secrets/*.yaml" -o -name "secrets.yaml" \) -type f -exec sops updatekeys --yes {} \;`

creation_rules:
  - path_regex: 'secrets/[^/]+\.(yaml|json|env|ini)$'
    key_groups:
      - age:
          - *user_dudeofawesome
          - *user_josh
          - *system_badlands
          - *system_crater-lake
          - *system_badlands-vm
          - *system_monongahela
          - *system_haleakala
          - *system_joshs-paciolan-laptop
          - *system_soto-server
          - *system_starling-vm

  # Users
  - path_regex: 'users/dudeofawesome/secrets\.yaml$'
    key_groups:
      - age:
          - *user_dudeofawesome
          - *system_badlands
          - *system_crater-lake
          - *system_badlands-vm
          - *system_monongahela
          - *system_haleakala
          - *system_soto-server
  - path_regex: 'users/josh/secrets\.yaml$'
    key_groups:
      - age:
          - *user_josh
          - *system_joshs-paciolan-laptop
          - *system_soto-server
          - *system_starling-vm

  # Systems
  - path_regex: 'hosts/nixos/badlands-vm/secrets\.yaml$'
    key_groups:
      - age:
          - *user_dudeofawesome
          - *system_badlands-vm
  - path_regex: 'hosts/nixos/monongahela/secrets\.yaml$'
    key_groups:
      - age:
          - *user_dudeofawesome
          - *system_monongahela
  - path_regex: 'hosts/nixos/haleakala/secrets\.yaml$'
    key_groups:
      - age:
          - *user_dudeofawesome
          - *system_haleakala
  - path_regex: 'hosts/nixos/soto-server/secrets\.yaml$'
    key_groups:
      - age:
          - *user_josh
          - *system_soto-server
  - path_regex: 'hosts/nixos/starling-vm/secrets\.yaml$'
    key_groups:
      - age:
          - *user_josh
          - *system_starling-vm

stores:
  yaml:
    indent: 2
  json:
    indent: 2
  json_binary:
    indent: 2
