vscode_version = "1.95.3"

extensions = [
  { extension_name = 'bookmarks', publisher_name = 'alefragnani' },
  { extension_name = 'gitlab-ci-ls', publisher_name = 'alesbrelih' },
  { extension_name = 'openscad', publisher_name = 'antyos' },
  { extension_name = 'beardedtheme', publisher_name = 'beardedbear' },
  { extension_name = 'markdown-mermaid', publisher_name = 'bierner' },
  { extension_name = 'vscode-fish', publisher_name = 'bmalehorn' },
  { extension_name = 'mermaid-markdown-syntax-highlighting', publisher_name = 'bpruitt-goddard' },
  { extension_name = 'vscode-tailwindcss', publisher_name = 'bradlc' },
  { extension_name = 'bruno', publisher_name = 'bruno-api-client' },
  { extension_name = 'solargraph', publisher_name = 'castwide' },
  { extension_name = 'gitignore', publisher_name = 'codezombiech' },
  { extension_name = 'nodejs-testing', publisher_name = 'connor4312' },
  { extension_name = 'systemd-unit-file', publisher_name = 'coolbear' },
  { extension_name = 'dart-code', publisher_name = 'dart-code' },
  { extension_name = 'flutter', publisher_name = 'dart-code' },
  { extension_name = 'vscode-eslint', publisher_name = 'dbaeumer' },
  { extension_name = 'vscode-dash', publisher_name = 'deerawan' },
  { extension_name = 'githistory', publisher_name = 'donjayamanne' },
  { extension_name = 'eslint-disable-snippets', publisher_name = 'drknoxy' },
  { extension_name = 'gitlens', publisher_name = 'eamodio' },
  { extension_name = 'editorconfig', publisher_name = 'editorconfig' },
  { extension_name = 'effect-vscode', publisher_name = 'effectful-tech' },
  { extension_name = 'vsc-material-theme-icons', publisher_name = 'equinusocio' },
  { extension_name = 'prettier-vscode', publisher_name = 'esbenp' },
  { extension_name = 'vscode-diff', publisher_name = 'fabiospampinato' },
  { extension_name = 'vscode-firefox-debug', publisher_name = 'firefox-devtools' },
  { extension_name = 'url-encode', publisher_name = 'flesler' },
  { extension_name = 'kotlin', publisher_name = 'fwcd' },
  { extension_name = 'lintlens', publisher_name = 'ghmcadams' },
  { extension_name = 'vscode-github-actions', publisher_name = 'github' },
  { extension_name = 'vscode-pull-request-github', publisher_name = 'github' },
  { extension_name = 'gitlab-workflow', publisher_name = 'gitlab' },
  { extension_name = 'go', publisher_name = 'golang' },
  { extension_name = 'rbs-syntax', publisher_name = 'gracefulpotato' },
  { extension_name = 'vscode-graphql', publisher_name = 'graphql' },
  { extension_name = 'vscode-graphql-execution', publisher_name = 'graphql' },
  { extension_name = 'vscode-graphql-syntax', publisher_name = 'graphql' },
  { extension_name = 'todo-tree', publisher_name = 'gruntfuggly' },
  { extension_name = 'terraform', publisher_name = 'hashicorp' },
  { extension_name = 'applescript', publisher_name = 'idleberg' },
  { extension_name = 'prettier-sql-vscode', publisher_name = 'inferrinizzard' },
  { extension_name = 'nix-ide', publisher_name = 'jnoortheen' },
  { extension_name = 'bash-ide-vscode', publisher_name = 'mads-hartmann' },
  { extension_name = 'kotlin', publisher_name = 'mathiasfrohlich' },
  { extension_name = 'dotenv', publisher_name = 'mikestead' },
  { extension_name = 'vscode-json5', publisher_name = 'mrmlnc' },
  { extension_name = 'vscode-scss', publisher_name = 'mrmlnc' },
  { extension_name = 'vscode-docker', publisher_name = 'ms-azuretools' },
  { extension_name = 'vscode-kubernetes-tools', publisher_name = 'ms-kubernetes-tools' },
  { extension_name = 'black-formatter', publisher_name = 'ms-python' },
  { extension_name = 'python', publisher_name = 'ms-python' },
  { extension_name = 'vscode-pylance', publisher_name = 'ms-python' },
  { extension_name = 'jupyter', publisher_name = 'ms-toolsai' },
  { extension_name = 'remote-ssh', publisher_name = 'ms-vscode-remote' },
  { extension_name = 'remote-ssh-edit', publisher_name = 'ms-vscode-remote' },
  { extension_name = 'remote-wsl', publisher_name = 'ms-vscode-remote' },
  { extension_name = 'hexeditor', publisher_name = 'ms-vscode' },
  { extension_name = 'remote-explorer', publisher_name = 'ms-vscode' },
  { extension_name = 'vsliveshare', publisher_name = 'ms-vsliveshare' },
  { extension_name = 'vscode-react-native', publisher_name = 'msjsdiag' },
  { extension_name = 'typescript-explorer', publisher_name = 'mxsdev' },
  { extension_name = 'color-highlight', publisher_name = 'naumovs' },
  { extension_name = 'vsc-gcode', publisher_name = 'novy' },
  { extension_name = 'vscode-jest', publisher_name = 'orta' },
  { extension_name = 'bun-vscode', publisher_name = 'oven' },
  { extension_name = 'material-icon-theme', publisher_name = 'pkief' },
  { extension_name = 'material-product-icons', publisher_name = 'pkief' },
  { extension_name = 'ruby-lsp', publisher_name = 'shopify' },
  { extension_name = 'ansible', publisher_name = 'redhat' },
  { extension_name = 'vscode-yaml', publisher_name = 'redhat' },
  { extension_name = 'partial-diff', publisher_name = 'ryu1kn' },
  { extension_name = 'node-modules-viewer', publisher_name = 'seeker-dk' },
  { extension_name = 'semanticdiff', publisher_name = 'semanticdiff' },
  { extension_name = 'markdown-preview-enhanced', publisher_name = 'shd101wyy' },
  { extension_name = 'ruby-lsp', publisher_name = 'shopify' },
  { extension_name = 'code-spell-checker', publisher_name = 'streetsidesoftware' },
  { extension_name = 'vscode-stylelint', publisher_name = 'stylelint' },
  { extension_name = 'even-better-toml', publisher_name = 'tamasfe' },
  { extension_name = 'pdf', publisher_name = 'tomoki1207' },
  { extension_name = 'vscode-mermaid-editor', publisher_name = 'tomoyukim' },
  { extension_name = 'lorem-ipsum', publisher_name = 'tyriar' },
  { extension_name = 'vscode-choosealicense', publisher_name = 'ultram4rine' },
  { extension_name = 'intellicode-api-usage-examples', publisher_name = 'visualstudioexptteam' },
  { extension_name = 'vscodeintellicode', publisher_name = 'visualstudioexptteam' },
  { extension_name = 'explorer', publisher_name = 'vitest' },
  { extension_name = 'quokka-vscode', publisher_name = 'wallabyjs' },
  { extension_name = 'vscode-gitops-tools', publisher_name = 'weaveworks' },
  { extension_name = 'change-case', publisher_name = 'wmaurer' },
  { extension_name = 'pretty-ts-errors', publisher_name = 'yoavbls' },
  { extension_name = 'markdown-all-in-one', publisher_name = 'yzhang' },
]
