vscode_version = "1.100.1"

extensions = [
  # languages
  'bruno-api-client.bruno', # missing

  'fwcd.kotlin', # missing

  'castwide.solargraph', # missing
  'gracefulpotato.rbs-syntax', # missing

  'graphql.vscode-graphql', # much more up-to-date
  'graphql.vscode-graphql-execution', # missing

  'idleberg.applescript', # missing

  'inferrinizzard.prettier-sql-vscode', # missing

  'jnoortheen.nix-ide', # much more up-to-date

  'mrmlnc.vscode-scss', # missing
  'bradlc.vscode-tailwindcss', # much more up-to-date

  'drknoxy.eslint-disable-snippets', # missing
  'ghmcadams.lintlens', # missing
  'effectful-tech.effect-vscode', # much more up-to-date
  'msjsdiag.vscode-react-native', # missing
  'connor4312.nodejs-testing', # missing
  'oven.bun-vscode', # missing
  'orta.vscode-jest', # missing
  'vitest.explorer', # missing
  'mxsdev.typescript-explorer', # missing
  'seeker-dk.node-modules-viewer', # missing

  'ms-toolsai.jupyter', # missing
  'eeyore.yapf', # missing

  'redhat.vscode-yaml', # ? https://github.com/nix-community/nix4vscode/issues/54
  'blueglassblock.better-json5', # missing
  'alesbrelih.gitlab-ci-ls', # missing

  'tomoyukim.vscode-mermaid-editor', # missing
  'bpruitt-goddard.mermaid-markdown-syntax-highlighting', # missing

  'terrastruct.d2', # missing

  'novy.vsc-gcode', # missing

  # utilities
  'flesler.url-encode', # missing
  'tyriar.lorem-ipsum', # missing
  'ultram4rine.vscode-choosealicense', # missing
  'yutengjing.open-in-external-app', # missing

  # views
  'deerawan.vscode-dash', # missing
  'fabiospampinato.vscode-diff', # missing
  'gitlab.gitlab-workflow', # much more up-to-date
  'ms-kubernetes-tools.vscode-kubernetes-tools', # quick updates
  'ms-vscode.remote-explorer', # missing
  'semanticdiff.semanticdiff', # missing
  'weaveworks.vscode-gitops-tools', # missing
  'github.vscode-github-actions', # quick updates
  'github.vscode-pull-request-github', # much more up-to-date
  'rooveterinaryinc.roo-cline', # missing

  # themes
  'beardedbear.beardedtheme', # missing
]
