#!/usr/bin/env nix
#! nix shell nixpkgs#bash nixpkgs#gnused github:nix-community/nix4vscode/632927533fcf28419c12c6394efdf6592f886e4f --command bash
# ^ https://github.com/nix-community/nix4vscode/issues/194
set -e

cd "$(dirname $0)"

input="extensions.toml"
output="extensions.nix"


# generate extension expressions
nix4vscode "$input" --output "$output"

# insert header about code generation
sed -i '1i# Do not modify this file!  It was generated by `update-extensions.sh` \
# and may be overwritten by future invocations.  Please make changes \
# to '"$input"' instead. \
' "$output"

# format output
nix fmt "$output"

echo "Updated extensions" >&2
