#!/usr/bin/env nix
#! nix shell nixpkgs#bash nixpkgs#gnused github:nix-community/nix4vscode/nix4vscode-v0.0.2 --command bash
set -e

nix4vscode --version

cd "$(dirname $0)"

input="extensions.toml"
output="extensions.nix"

# update vscode version
sed -i 's/^\(vscode_version = \)"[0-9]\+\.[0-9]\+\.[0-9]\+"$/\1"'"$(code --version | head -n 1)"'"/' "$input"
echo "Set vscode version" >&2

# generate extension expressions
echo "Generating extension expressions" >&2
nix4vscode --output "$output" "$input"

# insert header about code generation
sed -i '1i# Do not modify this file!  It was generated by `update-extensions.sh` \
# and may be overwritten by future invocations.  Please make changes \
# to '"$input"' instead. \
' "$output"

# format output
nix fmt "$output"

echo "Updated extensions" >&2
