{ config, lib, ... }:
let
  toolkit = config.hardware.nvidia-container-toolkit.package;
in
{
  hardware.nvidia-container-toolkit = {
    enable = true;
    # Match deviceIDStrategy in doa-cluster-flux's NVIDIA device-plugin release.
    device-name-strategy = "index";
  };

  # K3s uses our external containerd, so its runtime auto-detection does not
  # configure this daemon. Use the CDI specification generated by NixOS.
  virtualisation.containerd.settings.plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia =
    {
      runtime_type = "io.containerd.runc.v2";
      options.BinaryName = "${lib.getOutput "tools" toolkit}/bin/nvidia-container-runtime.cdi";
    };

  systemd.services.containerd = {
    requires = [ "nvidia-container-toolkit-cdi-generator.service" ];
    after = [ "nvidia-container-toolkit-cdi-generator.service" ];
  };

  # Flux owns the RuntimeClass and device-plugin release in doa-cluster-flux.
}
