{ ... }:
{
  imports = [
    ./1password-cli.nix
    ./1password-gui.nix
    ./aerospace.nix
    ./awscli.nix
    ./clock.nix
    ./discord.nix
    ./dock.nix
    ./docker-client.nix
    ./docker-desktop.nix
    ./file-json.nix
    ./finicky.nix
    ./git-fork.nix
    ./gitup.nix
    ./homebrew.nix
    ./kubeconfig.nix
    ./kubectl.nix
    ./moar.nix
    ./moonlight.nix
    ./podman-desktop.nix
    ./process-compose.nix
    ./qdrant.nix
    ./signal-desktop.nix
    ./slack.nix
    ./vscode.nix
    ./zoom-us.nix
  ];
}
