name: Check

on:
  push:
    branches: [main]
    tags-ignore: ['*']
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  lint-flake:
    name: Lint Flake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@c251f11beeb14adb5490acc1b192175d8ae0e95e # main

      - name: Enable Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@77f0204d0bda4ee1e0bad6174bbdb9385cbf2049 # main
        with:
          use-flakehub: disabled
          use-gha-cache: enabled

      - name: Lint Flake
        shell: bash
        run: |
          nix flake check \
            --all-systems \
            --keep-going \
            ;
